name: Build Statics

on: [push, pull_request]

jobs:
  build:
    name: Generate static pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Generate TV HTML
        run: |
          pip install imdbpy
          python tv/generate.py tv/shows/data.json tv/index.html

      - name: Generate Resume HTML
        run: |
          cat resume/index.html | sed 's/<div class="resume">/<div>/' > resume/resume.html

      - name: Convert
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./resume/resume.html
          outputFile: ./resume.pdf
          pdfOptions: '{}'

      - name: Commit PDF
        run: |
          git config --global user.name 'TV page builder'
          git config --global user.email 'tv-page-builder-batuhan@users.noreply.github.com'
          git add .
          git commit -am "Build tv pages" --allow-empty
          git push
