name: PDF builder

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate Resume HTML
        run: |
          cat resume/index.html | sed 's/<div class="resume">/<div>/' > resume/resume.html

      - name: Convert
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./resume/resume.html
          outputFile: ./resume.pdf
          pdfOptions: '{}'

      - name: Commit PDF
        run: |
          git config --global user.name 'PDF Builder'
          git config --global user.email 'pdf-builder-batuhan@users.noreply.github.com'
          git add resume.pdf
          git commit -am "Export the PDF"
          git push
